services:
  bot:
    build: 
      context: .
      dockerfile: ./bot/Dockerfile
    image: classifiedhambot
  monitor:
    build:
      context: .
      dockerfile: ./monitor/Dockerfile
    image: monitor
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    image: api